### ISSUE TITLE
Starting parity with other options (tracing, archive)

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DNP_ETHCHAIN#16]
Hi! @tjayrush and I are very excited about bringing QuickBlocks to dappnode. We want to ask you about node startup options.

I notice in the dockerfile that parity is started like so:

```
ENTRYPOINT parity --jsonrpc-port 8545 --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-cors all --ws-interface 0.0.0.0 --ws-port 8546 --ws-origins all --ws-hosts all --ws-max-connections 1000 --cache-size 3072 --warp-barrier 6500000 $EXTRA_OPTS
```

**For full functionality, QuickBlocks depends on a node that has tracing enabled.** We also start with archive-style pruning, but that's less of a concern.

We use the following flags when starting parity:

```sh
parity --tracing on --pruning archive --db-path=/datadir --no-periodic-snapshot --db-compaction=ssd
```

Do you think it's best that we instruct our dappnode users to add to their EXTRA_OPTS in [ethchain.dnp.dappnode.eth.env](https://github.com/dappnode/DNP_ETHCHAIN/blob/master/ethchain.dnp.dappnode.eth.env)?

e.g.

```sh
EXTRA_OPTS="--tracing on"
```

Or, is there a possibility that we could have tracing enabled by default? Thanks for reading and we're excited to hear your thoughts.

**Comment by tjayrush** [comment]
Slight clarification. `--pruning archive` is not required for QuickBlocks to run. Only `--tracing on` is required for it to run. The `--pruning archive` option need nearly 2TB of disc space at this point. `--tracing on` adds about 180GB. `--pruning archive` allows for a verification step which is not possible without historical balances.

**Comment by eduadiez** [comment]
Hi!

We added that functionality thinking about you and that it could be useful for QuickBlocks ;-)

This thought to only have to go to [Admin -> System -> Ethchain](http://my.admin.dnp.dappnode.eth/#/system/ethchain.dnp.dappnode.eth) and write in the EXTRA_OPTS the options you need.

<img width="1690" alt="screenshot 2018-12-10 at 18 24 23" src="https://user-images.githubusercontent.com/20141918/49749890-c2a3fe00-fca9-11e8-86af-0f4e74a2e0fd.png">


By clicking on `update environment variables` the package should take these options and restart it.

In the case of `-- tracing on` the `Remove volumes` may be necessary for the synchronization to start again.
