### ISSUE TITLE
docker-compose.yml / docker-compose-ethchain.yml

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DNP_ETHCHAIN#17]
Hi guys, noticed documentation references docker-compose-ethchain.yml, but the file in the repo is docker-compose.yml. It looks like the files in the other DNP repos are simply docker-compose.yml.  I'd be happy to file a PR changing the documentation here if it'd be helpful.

**Comment by eduadiez** [comment]
Hi @wildmolasses! yes, that would be awesome! thank you

**Comment by dapplion** [comment]
Thank you for your contribution @wildmolasses ! I will review your PRs.

**Comment by dapplion** [comment]
Merged
