### ISSUE TITLE
Open RPC port in docker-compose.yml

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DNP_ETHCHAIN#18]
Map a port to 8545 in docker-compose.yml so that other containers can run RPC queries against the node.

Related: open a port for websockets (8546)

Apologies if I am overloading the issues here. I thought you might want an early user to be loud instead of quiet. I'm happy to do this configuration locally instead of changing defaults here. Also, I am a docker noob, so if you can recommend a way to access the rpc without opening a port in docker-compose.yml, I'd be grateful. Anyway, if you do want to open a port by default, I'm happy to open a PR if it would be helpful. I see the way it's done in other DNPs and I can match the style.

**Comment by dapplion** [comment]
Hi @wildmolasses, glad you are more loud than quieter, please share without fear any issues and proposals you have with us.

In a normal scenario you want to have restricted access to your node's RPC. Opening ports 8545 and 8546 to the world wide web can jeopardize the security of your node and open the door to bad actors. If you connect to your DAppNode's VPN connection you can access it's ethchain RPC by issuing queries to this links:

 ```
http://my.ethchain.dnp.dappnode.eth:8545
ws://my.ethchain.dnp.dappnode.eth:8546
```

It would make sense to open the ports if you offered some sort of infura-type service, but that's doesn't make sense currently without an incentivization mechanism. Please let me know if you think otherwise or if you have any more ideas on this.

**Comment by wildmolasses** [comment]
@dapplion!!!!! Thank you for the invitation to share. I read what you say about the VPN, something I didn't understand at all. The VPN solution will be perfect. All I needed was an endpoint (such as http://my.ethchain.dnp.dappnode.eth:8545) to connect to. It seems the VPN solution solves this. Thanks again.

**Comment by wildmolasses** [comment]
Hey @dapplion. I am testing out my trueblocks container locally on docker for mac. I run the DNP_ETHCHAIN container. Then I put my trueblocks container onto the same network (`dnp_ethchain_network`). Here is my experimental Dockerfile:

```dockerfile
version: "3.4"

networks:
  dnp_ethchain_network:
    external: true

volumes:
  trueblocksdnpdappnodeeth_data: {}

services:
  trueblocks.dnp.dappnode.eth:
    build: ./build
    image: trueblocks.dnp.dappnode.eth:0.0.1
    container_name: DAppNodePackage-trueblocks.dnp.dappnode.eth
    restart: always
    volumes:
      - trueblocksdnpdappnodeeth_data:/root/quickBlocks-data
    networks:
      - dnp_ethchain_network
```

I then use 172.33.1.6:8545 (the ipv4 address of DNP_ETHCHAIN) as my RPC endpoint.

I only did this as a quick way to see trueblocks working against the node. It was a success. But this is not the recommended way. Instead you recommend I use http://my.ethchain.dnp.dappnode.eth:8545 as my endpoint. 

Is there a way on *mac for docker* where I can run the necessary containers to run locally the recommended endpoint, http://my.ethchain.dnp.dappnode.eth:8545 endpoint?

Anyway, tomorrow we open @tjayrush's dappnode, and can begin experimenting directly on the machine.

**Comment by sponnet** [comment]
@wildmolasses 
Hey Ed,

Awesome to hear that you're making a trueblocks container on dappnode !!!

Stefaan

**Comment by wildmolasses** [comment]
Thanks @dapplion, reposting some of our chat here:

**Me:**
Right now, idea is that trueblocks container runs on same machine as dappnode.

**You:**
In that case you can use the same urls but you need to connect to the already existing dappnode network. See this docker compose as reference
```
version: '3.4'
services:
    yourdnp.public.dappnode.eth:
        container_name: DAppNodePackage-yourdnp.public.dappnode.eth
        image: 'yourdnp.public.dappnode.eth:0.0.3'
        networks:
            - dncore_network
        dns: 172.33.1.2
networks:
    dncore_network:
        external: true
```
The intented purpose is that if you want to run a dockerized application within DAppNode, that's a DNP (DAppNode Package). We have developed a SDK that will help solve all this hastle. Please take a look at the guide and examples:
https://github.com/dappnode/DAppNodeSDK

**Comment by sponnet** [comment]
If you want a walkthrough, ping me and I can show you over a video call how to set it up step by step ... Just did the whole cycle for that göerli validator package..

**Comment by Shelpin** [comment]
Thanks everybody!!! did this solve your doubt @wildmolasses ??
