### ISSUE TITLE
Incorrect default port configuration (fresh install)

### ISSUE THREAD

**Issue by uniconstructor** [dappnode/DNP_ETHCHAIN#58]
I am noticed that default port configuration differs from Docker and package config.

Steps to reproduce:
1) make fresh installation of dappnode
2) open Ethchain package page
3) switch to "Ports" tab: http://my.dappnode/#/packages/ethchain.dnp.dappnode.eth/ports

Expected result: default ports are exactly set from config values:
 - [package config](https://github.com/dappnode/DNP_ETHCHAIN/blob/fa1f1155351e472f5ac37432b50b1f1aa037191c/dappnode_package.json#L18)
 - [docker compose](https://github.com/dappnode/DNP_ETHCHAIN/blob/fa1f1155351e472f5ac37432b50b1f1aa037191c/docker-compose.yml#L26)

Actual result: port 30303 set incorrectly:

![dappnode-incorrect ports](https://user-images.githubusercontent.com/1384545/71550805-c22bf180-29e9-11ea-923b-e11f54070e6d.png)

**Comment by uniconstructor** [comment]
UPD: looks like this bug related only to UI form: docker container runs with correct options:

![Снимок экрана от 2019-12-29 05-13-55](https://user-images.githubusercontent.com/1384545/71551501-366e9100-29fa-11ea-9676-e8c6d026e8fd.png)

**Comment by dapplion** [comment]
Fixed in previous releases
